fix MySQL bit type does not support exceptions.
The following error occurred when I was generating phpdocs.
```
Exception: Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
Could not analyze class App\Models\UserModel.
```
By checking the source code, I found out that it was a type mapping problem, so I added this line of code.