Add error code mapping for "no default value" to MySQL driver
When following error message is shown, then it will get converted to the
correct Exception classs of NotNullConstraintViolationException:

  PDOException: SQLSTATE[HY000]: General error: 1364 Field '...' doesn't have a
  default value